---
title: Nick Strayer's Resume"
author: Nick Strayer
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['styles.css']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true

---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  select(-in_resume) %>% 
  mutate_all(fill_nas) %>% 
  arrange(desc(end)) %>% 
  mutate(
    id = 1:n(),
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) %>% 
  nest(data = c(-id, -section)) %>% 
  mutate()



```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> nick.strayer@gmail.com
- <i class="fa fa-twitter"></i> NicholasStrayer
- <i class="fa fa-github"></i> github.com/nstrayer
- <i class="fa fa-link"></i> [nickstrayer.me](http://nickstrayer.me/)
- <i class="fa fa-phone"></i> (734) 645-0110



Skills {#skills}
--------------------------------------------------------------------------------


Highly experienced in


- R 
- Python
- Javascript

Experience with


- Bash
- SQL
- C++
- AWK


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Last updated on `r Sys.Date()`.




Main
================================================================================

Nick Strayer {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "I have made [visualizations viewed by hundreds of thousands of people](https://www.nytimes.com/interactive/2016/08/26/us/college-student-migration.html), [sped up query times for 25 terabytes of data by an average of 4,800 times](https://livefreeordichotomize.com/2019/06/04/using_awk_and_r_to_parse_25tb/), and built [packages for R](https://github.com/nstrayer/shinysense) that let you [do magic](http://nickstrayer.me/dataDayTexas/).

Currently searching for a data science position that allows me build tools using visualization and machine learning to help people explore and understand their data. 
"

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Positions Held {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```

